### PR TITLE
Optimized assets, partial pl_pl.json, executable gradlew, updated gradle.properties, loom 0.9.

### PR DESCRIPTION
**Pull request by RDKRACZ**
Lossless - I used optipng (`optipng -o7 -strip all *.png`).

### CODE REVIEW

**Comment by ExcessiveAmountsOfZombies** [comment]
i'm not sure i want to accept compressions of the textures, sorry man

**Comment by Micalobia** [comment]
The compression is lossless, so there isn't any quality loss and you get smaller files for free

**Comment by RDKRACZ** [comment]
So, should this be closed or redone? Assets directory size goes from 1,5 MB to 539,4 kB

**Comment by ExcessiveAmountsOfZombies** [comment]
if you split it into just the assets reduction i'll merge it

**Pull request closed without merging**
