### PR TITLE
Update de_de.json

### PR DESCRIPTION
**Pull request by Motschen**
Fixed some spelling errors (thanks @2xsaiko) :)

### CODE REVIEW

**Comment by 2xsaiko** [comment]
No problem! Though, what about the other stuff I wrote in #1?

**Comment by Motschen** [comment]
What other stuff do you mean exactly?

**Comment by 2xsaiko** [comment]
I had more corrections that aren't in this PR, for example Pfirsisch -> Pfirsich

**Comment by Motschen** [comment]
Oh, sorry, they were hidden...

**Comment by 2xsaiko** [comment]
Ah, no problem :+1:

**Comment by ExcessiveAmountsOfZombies** [comment]
I'll merge this again with 1.0.3 if it's all ready to go

**Pull request merged**
