### PR TITLE
Tech Reborn Integration

### PR DESCRIPTION
**Pull request by JiroCab**
A attempt to make Croptopia work with Tech Reborn

Note: Idk Basalt dust to salt is logical tho

### CODE REVIEW

**Comment by ExcessiveAmountsOfZombies** [comment]
As mentioned in #128 I don't believe I can add these on my end unless written in code? Unlike forge I don't believe fabric has a conditional recipe system.

**Comment by JiroCab** [comment]
Ah i didn't thought of that 
Tho a sloppy work around could be to ship or add optional datapacks for each specific modloader

**Comment by BrekiTomasson** [comment]
Fabric does have a conditional recipe system, but the have to be written in code, not in the JSON files. Take a look at what I'm doing in one of my mods as an example:

I have a `RecipeManagerMixin.json` mixin that loads all my custom recipes after they've been defined: https://github.com/FettLol/FettLolUtilMod/blob/master/src/main/java/net/fettlol/mixin/RecipeManagerMixin.java

The recipes all go into a HashMap in this file https://github.com/FettLol/FettLolUtilMod/blob/master/src/main/java/net/fettlol/init/FettlolRecipes.java and as you can see, there are plenty of recipes defined there with conditionals, such as this one that adds a recipe for Tridents, but only if the mod Adorn is loaded (since one of the ingredients comes from Adorn):

```
private static void addTridentRecipe() {
    if (ModIntegrations.isAdornLoaded) {
        CUSTOM_RECIPES.put(
            "extras/trident",
            RecipeHelper.createShapedRecipe(
                Lists.newArrayList('S', 'A', 'C', 'P'),
                Lists.newArrayList(
                    new Identifier("minecraft", "prismarine_shard"),
                    new Identifier(UtilMod.MOD_ID, "aquamarine_gem"),
                    new Identifier("minecraft", "conduit"),
                    new Identifier(ModIntegrations.ADORN, "prismarine_brick_post")
                ),
                Lists.newArrayList("item", "item", "item", "item"),
                Lists.newArrayList("SSS", "ACA", " P "),
                new Identifier("minecraft", "trident")
            )
        );
    }
}
```

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you for the PR, I do want to avoid creating recipes in code if possible, so after coming up with strange ideas in my head I just asked around and apparently the fabric API has a system for this in place! https://github.com/ExcessiveAmountsOfZombies/Croptopia/commit/33095d092fbd342f13dec7447b734d43d82099ba

**Pull request merged**
